# Exported from Render on 2025-05-15T14:58:02Z
services:
- type: web
  name: simple-canny
  runtime: python
  repo: https://github.com/dmoyer22/simple-canny
  plan: free
  region: virginia
  buildCommand: pip install -r requirements.txt
  startCommand: python -m uvicorn CannyEdgeDetection:app --host 0.0.0.0 --port 8000
  autoDeployTrigger: commit
version: "1"
